### ISSUE TITLE
NULL reference exceptions during test discovery

### ISSUE THREAD

**Issue by wasabinza** [csoltenborn/GoogleTestAdapter#178]
Since recent upgrades I have been receiving a number of new null reference exceptions during test discovery.  Probably once again due to the fact that our projects link a number of dll's that were compiled with debug symbols but those pdb files may not currently be available.
In PeParser.cs > ProcessImports-> AnonymousMethod the directoryEntry is 0x00000,
so maybe it just needs protection with an 
if (directoryEntry)

[13/11/2017 9:36:20 AM Error] ERROR: Exception while discovering tests: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GoogleTestAdapter.DiaResolver.PeParser.<>c__DisplayClass2_0.<ProcessImports>b__0(LOADED_IMAGE image)
   at GoogleTestAdapter.DiaResolver.PeParser.ParsePeFile(String executable, ILogger logger, Action`1 action)
   at GoogleTestAdapter.DiaResolver.PeParser.ProcessImports(String executable, ILogger logger, Func`2 predicate)
   at GoogleTestAdapter.DiaResolver.PeParser.FindImport(String executable, String import, StringComparison comparisonType, ILogger logger)
   at GoogleTestAdapter.GoogleTestDiscoverer.IsGoogleTestExecutable(String executable, String customRegex, ILogger logger)
   at GoogleTestAdapter.GoogleTestDiscoverer.<>c__DisplayClass6_0.<DiscoverTests>b__0()
   at GoogleTestAdapter.Settings.SettingsWrapper.ExecuteWithSettingsForExecutable(String executable, Action action, ILogger logger)
   at GoogleTestAdapter.GoogleTestDiscoverer.DiscoverTests(String executable, ITestFrameworkReporter reporter, SettingsWrapper settings, ILogger logger, IDiaResolverFactory diaResolverFactory)
   at GoogleTestAdapter.GoogleTestDiscoverer.<>c__DisplayClass5_0.<DiscoverTests>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at GoogleTestAdapter.Helpers.Utils.SpawnAndWait(Action[] actions, Int32 timeoutInMs)
   at GoogleTestAdapter.GoogleTestDiscoverer.DiscoverTests(IEnumerable`1 executables, ITestFrameworkReporter reporter)
   at GoogleTestAdapter.TestAdapter.TestDiscoverer.DiscoverTests(IEnumerable`1 executables, IDiscoveryContext discoveryContext, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at GoogleTestAdapter.DiaResolver.PeParser.<>c__DisplayClass2_0.<ProcessImports>b__0(LOADED_IMAGE image)
   at GoogleTestAdapter.DiaResolver.PeParser.ParsePeFile(String executable, ILogger logger, Action`1 action)
   at GoogleTestAdapter.DiaResolver.PeParser.ProcessImports(String executable, ILogger logger, Func`2 predicate)
   at GoogleTestAdapter.DiaResolver.PeParser.FindImport(String executable, String import, StringComparison comparisonType, ILogger logger)
   at GoogleTestAdapter.GoogleTestDiscoverer.IsGoogleTestExecutable(String executable, String customRegex, ILogger logger)
   at GoogleTestAdapter.GoogleTestDiscoverer.<>c__DisplayClass6_0.<DiscoverTests>b__0()
   at GoogleTestAdapter.Settings.SettingsWrapper.ExecuteWithSettingsForExecutable(String executable, Action action, ILogger logger)
   at GoogleTestAdapter.GoogleTestDiscoverer.DiscoverTests(String executable, ITestFrameworkReporter reporter, SettingsWrapper settings, ILogger logger, IDiaResolverFactory diaResolverFactory)
   at GoogleTestAdapter.GoogleTestDiscoverer.<>c__DisplayClass5_0.<DiscoverTests>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by csoltenborn** [comment]
Thanks for your report! Checking whether `directoryEntry` is `NULL` indeed seems to be the solution here...

**Comment by csoltenborn** [comment]
@wasabinza When closing the issue, I forgot to mention that there should be a [warning](https://github.com/csoltenborn/GoogleTestAdapter/blob/2f92e7b457066534e5263388699fef53c49492d2/GoogleTestAdapter/DiaResolver/PeParser.cs#L147) now in Debug mode if test discovery would have crashed before, and that warning should tell why `ImageDirectoryEntryToData()` returned `null`. I would be curious about the cause since I thought this could never happen...
