### ISSUE TITLE
Does not install on Windows 10 with Visual Studio 2013 (with fix)

### ISSUE THREAD

**Issue by RaymondKHessel** [csoltenborn/GoogleTestAdapter#29]
Running the installer for 0.3.0 (or 0.2.3) fails on a Windows 10 system with Visual Studio 2013 with the installation log below. Changing the line
```
<Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="4.5" />
```
to
```
<Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="[4.5,4.6]" />
```
in the extension.vsixmanifest file in the .vsix package fixes the issue

Presumably this is the same as changing the corresponding line in the GoogleTestAdapter\VsPackage\source.extension.vsixmanifest file of the VsPackage project (or some settings in the project), couldn't test that though because I have VS 2015 not installed.

```
24/02/2016 11:31:26 - Microsoft VSIX Installer
24/02/2016 11:31:26 - -------------------------------------------
24/02/2016 11:31:27 - Initializing Install...
24/02/2016 11:31:27 - Extension Details...
24/02/2016 11:31:27 - 	Identifier      : GoogleTestAdapterVSIX.e57b9720-dfde-4baa-bcb5-0f75772012b4
24/02/2016 11:31:27 - 	Name            : Google Test Adapter
24/02/2016 11:31:27 - 	Author          : Christian Soltenborn, Jonas Gefele
24/02/2016 11:31:27 - 	Version         : 0.2.3.203
24/02/2016 11:31:27 - 	Description     : Adds support for the C++ unit testing framework Google Tests.
24/02/2016 11:31:27 - 	Locale          : en-US
24/02/2016 11:31:27 - 	MoreInfoURL     : https://github.com/csoltenborn/GoogleTestAdapter
24/02/2016 11:31:27 - 	InstalledByMSI  : False
24/02/2016 11:31:27 - 	SupportedFrameworkVersionRange : [4.5]
24/02/2016 11:31:27 - 
24/02/2016 11:31:27 - 	Supported Products : 
24/02/2016 11:31:27 - 		Microsoft.VisualStudio.Community
24/02/2016 11:31:27 - 			Version : [12.0,14.0]
24/02/2016 11:31:27 - 		Microsoft.VisualStudio.Pro
24/02/2016 11:31:27 - 			Version : [12.0,14.0]
24/02/2016 11:31:27 - 		Microsoft.VisualStudio.Enterprise
24/02/2016 11:31:27 - 			Version : [12.0,14.0]
24/02/2016 11:31:27 - 		Microsoft.VisualStudio.Ultimate
24/02/2016 11:31:27 - 			Version : [12.0,14.0]
24/02/2016 11:31:27 - 
24/02/2016 11:31:27 - 	References      : 
24/02/2016 11:31:27 - 		-------------------------------------------------------
24/02/2016 11:31:27 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
24/02/2016 11:31:27 - 		Name         : Visual Studio MPF 11.0
24/02/2016 11:31:27 - 		Version      : [11.0]
24/02/2016 11:31:27 - 		MoreInfoURL  : 
24/02/2016 11:31:27 - 		Nested       : No
24/02/2016 11:31:27 - 
24/02/2016 11:31:27 - 
24/02/2016 11:31:27 - Searching for applicable products...
24/02/2016 11:31:27 - Found installed product - Microsoft Visual Studio Community 2013
24/02/2016 11:31:27 - The extension with ID 'GoogleTestAdapterVSIX.e57b9720-dfde-4baa-bcb5-0f75772012b4' is not installed to Microsoft Visual Studio Community 2013.
24/02/2016 11:31:27 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
24/02/2016 11:31:27 - Found installed product - Global Location
24/02/2016 11:31:29 - The following target products have been selected...
24/02/2016 11:31:29 - 	Microsoft Visual Studio Community 2013
24/02/2016 11:31:29 - 
24/02/2016 11:31:29 - Beginning to install extension to Microsoft Visual Studio Community 2013...
24/02/2016 11:31:29 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'Google Test Adapter' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

**Comment by csoltenborn** [comment]
Thanks for the detailed bug report! Give us a couple of days to look into it...

**Comment by csoltenborn** [comment]
@RaymondKHessel We have implemented your patch - can you please double check whether the extension now installs into your environment? You can download the VSIX [here](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.3.0.307/artifacts).

**Comment by RaymondKHessel** [comment]
Works fine. Thanks!

**Comment by angocor** [comment]
I am having this same issue. 

I am using Visual Studio 2013, Windows 10 and .net Framework version 4.7.  Is it possible to extend the patch to .net framework version 4.7?.

Thanks.

**Comment by csoltenborn** [comment]
Shouldn't be a problem at all - I have just created #161 for this. I will be on vacation from 8/31 on - would you be willing to test a build? I would then release 0.10.2 beforehand...
