### ISSUE TITLE
Crash during the TestResults on VS2013

### ISSUE THREAD

**Issue by cyrilbesse** [csoltenborn/GoogleTestAdapter#54]
Hi,
When I use the version VS2013 of vstest.console.exe, sometime I obtain a crash. I don't succeed to debug the dll to understand the issue. See below the call stack
Nota: I will propose a fix which tests if the argument is null, but I don't know if it is the better way to fix it.
I use the GoogleTestAdapter v0.6.
I don't have the crash in using vstest.console.exe of VS2015.

Call stack of the exception:
```
Information: Running 14 tests...

Error: ERROR: Exception while running tests: System.ArgumentNullException: Value cannot be null.
Parameter name: str
   at System.Text.RegularExpressions.Regex.Escape(String str)
   at GoogleTestAdapter.TestResults.ErrorMessageParser..ctor(String baseDir) in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\TestResults\ErrorMessageParser.cs:line 46
   at GoogleTestAdapter.TestResults.ErrorMessageParser..ctor(XmlNodeList failureNodes, String baseDir) in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\TestResults\ErrorMessageParser.cs:line 37
   at GoogleTestAdapter.TestResults.XmlTestResultParser.ParseTestResult(XmlNode testcaseNode) in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\TestResults\XmlTestResultParser.cs:line 110
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at GoogleTestAdapter.TestResults.XmlTestResultParser.ParseTestResults() in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\TestResults\XmlTestResultParser.cs:line 62
   at GoogleTestAdapter.TestResults.XmlTestResultParser.GetTestResults() in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\TestResults\XmlTestResultParser.cs:line 39
   at GoogleTestAdapter.Runners.SequentialTestRunner.CollectTestResults(IEnumerable`1 testCasesRun, String resultXmlFile, List`1 consoleOutput, String baseDir) in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\Runners\SequentialTestRunner.cs:line 101
   at GoogleTestAdapter.Runners.SequentialTestRunner.RunTestsFromExecutable(String executable, IEnumerable`1 allTestCases, IEnumerable`1 testCasesToRun, String baseDir, String userParameters, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher) in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\Runners\SequentialTestRunner.cs:line 83
   at GoogleTestAdapter.Runners.SequentialTestRunner.RunTests(IEnumerable`1 allTestCases, IEnumerable`1 testCasesToRun, String baseDir, String userParameters, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher) in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\Runners\SequentialTestRunner.cs:line 44
   at GoogleTestAdapter.Runners.PreparingTestRunner.RunTests(IEnumerable`1 allTestCases, IEnumerable`1 testCasesToRun, String baseDir, String userParameters, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher) in D:\Git\GoogleTestAdapter\GoogleTestAdapter\Core\Runners\PreparingTestRunner.cs:line 47

Information: Test execution completed.
```
Kind regards
Cyril

**Comment by cyrilbesse** [comment]
I am beginner on GitHub. 
I have a fix on a local branch, but I don't succeed to publish it.

`Error encountered while publishing branch to the remote repository: Response status code does not indicate success: 403 (Forbidden).`

**Comment by csoltenborn** [comment]
Hi,

thanks for reporting the bug and even a fix! However, you cannot push directly into our repository. You need to

1. fork our repository (afterwards, you have an own GoogleTestAdapter project associated with your GitHub account),
1. clone that repository to your local machine,
1. fix the bug locally,
1. push your bugfix to your repository, and finally
1. open a pull request for our repository.

We wll then review your fix and - if everything is fine - pull your fix into our repository. This has the advantage that before we even look at it, your fix will go through our CI server, which checks whether the project still builds, and whether all tests are still green.

Note that this sounds rather complicated, but is not complicated at all (in fact, it's pure magic and the main reason why GitHub rules the Open Source world by now, so it's probably worth having a look at that process anyways).

See also [Fork a Repo](https://help.github.com/articles/fork-a-repo/) and [Using pull requests](https://help.github.com/articles/using-pull-requests/).

A finally note: We will most likely release a new version at the beginning of next week, so if you are able to perform your pull request until, say, Sunday, it will (if it's fine) be released very quickly.

All the best,
Christian

**Comment by cyrilbesse** [comment]
Hello,
I open a pull request since about 8 days. I have no answer. Do I do something wrong in the process ?

Regards
Cyril

**Comment by csoltenborn** [comment]
Hi,

yes, you seem to have done something wrong, since we do not have any open pull requests:

![image](https://cloud.githubusercontent.com/assets/352576/16355144/44f98b10-3aae-11e6-9009-97e127d0aa00.png)

Sorry, not sure where I could help you with this without further information... have you followed the according GitHub instructions?

All the best
Christian

**Comment by csoltenborn** [comment]
@cyrilbesse I've had a quick look at the changes on your fork - they look fine in general (and thanks for adding an according uni test!), although it would be nice to better understand the circumstances under which the string is null...

If you want, I can manually add these changes to our repository (it's not that much, as you know). However, in that case you will not appear as author in our commit log. Let me know if you prefer this way, or if you want to give pull requests another chance...

**Comment by cyrilbesse** [comment]
Hi @csoltenborn ,
I have understood ! I had not taken the correct branch, during my 1st pull request. Now it is correct because I succeed to see it in your repository.

Thanks for your patience

**Comment by csoltenborn** [comment]
@cyrilbesse Thanks for the pull request! Issue solved, I hope...
