### ISSUE TITLE
EXPECT_NEAR assertion failure stops test run

### ISSUE THREAD

**Issue by KevinLucidyne** [csoltenborn/GoogleTestAdapter#69]
In this case I've selected four tests.  The first test fails an EXPECT_NEAR assertion.  The remaining 3 tests never run because of a GTA exception.

```
Running 16 tests...
>>>>>>>>>>>>>>> Output of command 'C:\Users\Kevin\dev\IPSight\SegNet\caffe-segnet\Build\x64\Debug\test_all.exe --gtest_output="xml:C:\Users\Kevin\AppData\Local\Temp\tmpD01.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=0 --gtest_filter=DenseImageDataLayerTest/0.*:DenseImageDataLayerTest/1.*:DenseImageDataLayerTest/3.*:DenseImageDataLayerTest/2.*:'
Cuda number of devices: 1
Current device id: 0
Current device name: Quadro M1000M
Note: Google Test filter = DenseImageDataLayerTest/0.*:DenseImageDataLayerTest/1.*:DenseImageDataLayerTest/3.*:DenseImageDataLayerTest/2.*:
[==========] Running 16 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from DenseImageDataLayerTest/0, where TypeParam = struct caffe::CPUDevice<float>
[ RUN      ] DenseImageDataLayerTest/0.TestRead
..\..\src\caffe\test\test_dense_image_data_layer.cpp(100): error: The difference between sum / this->blob_top_label_->count() and 1.475104 is 0.88506236257934567, which exceeds 1e-4, where
sum / this->blob_top_label_->count() evaluates to 0.5900416374206543,
1.475104 evaluates to 1.475104, and
1e-4 evaluates to 0.0001.
..\..\src\caffe\test\test_dense_image_data_layer.cpp(100): error: The difference between sum / this->blob_top_label_->count() and 1.475104 is 0.88506236257934567, which exceeds 1e-4, where
sum / this->blob_top_label_->count() evaluates to 0.5900416374206543,
1.475104 evaluates to 1.475104, and
1e-4 evaluates to 0.0001.
[  FAILED  ] DenseImageDataLayerTest/0.TestRead, where TypeParam = struct caffe::CPUDevice<float> (958 ms)
[ RUN      ] DenseImageDataLayerTest/0.TestResize
<<<<<<<<<<<<<<< End of Output
Warning: Test result file C:\Users\Kevin\AppData\Local\Temp\tmpD01.tmp could not be parsed (completely) - your test executable has probably crashed. Exception message: Root element is missing.
Collected 0 test results from XML result file 'C:\Users\Kevin\AppData\Local\Temp\tmpD01.tmp'
ERROR: Exception while running tests: System.ArgumentException: Search pattern cannot contain ".." to move up directories and can be contained only internally in file/directory names, as in "a..b".
   at System.IO.Path.CheckSearchPattern(String searchPattern)
   at System.IO.FileSystemEnumerableIterator`1.NormalizeSearchPattern(String searchPattern)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at GoogleTestAdapter.Helpers.SourceFileFinder.CollectTestAndTracesData(String file)
   at GoogleTestAdapter.Helpers.SourceFileFinder.Find(String file, Func`2 isMatchingAbsoluteFile)
   at GoogleTestAdapter.Helpers.SourceFileFinder.Find(String file, TestCase testCase)
   at GoogleTestAdapter.TestResults.ErrorMessageParser.CreateErrorMessageAndStacktrace(String& errorMessage, String& stackTrace, Int32 msgId)
   at GoogleTestAdapter.TestResults.ErrorMessageParser.HandleMultipleFailures()
   at GoogleTestAdapter.TestResults.ErrorMessageParser.Parse()
   at GoogleTestAdapter.TestResults.StandardOutputTestResultParser.CreateTestResult(Int32 indexOfTestcase)
   at GoogleTestAdapter.TestResults.StandardOutputTestResultParser.GetTestResults()
   at GoogleTestAdapter.Runners.SequentialTestRunner.CollectTestResults(IEnumerable`1 testCasesRun, String resultXmlFile, List`1 consoleOutput, String baseDir, SourceFileFinder finder)
   at GoogleTestAdapter.Runners.SequentialTestRunner.RunTestsFromExecutable(String executable, IEnumerable`1 allTestCases, IEnumerable`1 testCasesToRun, String baseDir, String userParameters, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher)
   at GoogleTestAdapter.Runners.SequentialTestRunner.RunTests(IEnumerable`1 allTestCases, IEnumerable`1 testCasesToRun, String baseDir, String userParameters, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher)
   at GoogleTestAdapter.Runners.PreparingTestRunner.RunTests(IEnumerable`1 allTestCases, IEnumerable`1 testCasesToRun, String baseDir, String userParameters, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher)
Google Test execution completed, overall duration: 00:00:06.6616301.
========== Run test finished: 0 run (0:00:08.6137258) ==========

```

**Comment by KevinLucidyne** [comment]
Issue also occurs on command line. So this may already be covered by a previous bug.  Feel free to close if that's the case.

**Comment by csoltenborn** [comment]
GTA is not involved when you execute the test on the command line, so no surprise about that. However, that exception might be a potential problem, so we will certainly look into it... Thanks for reporting - you (with your weird test suite) turn into great testers for our adapter :-)

Is this with the custom version I provided for you, or with the latest release version?

**Comment by KevinLucidyne** [comment]
I'm using it at your suggestion to get the debug dumps of errors.

**Comment by csoltenborn** [comment]
Nope - I pointed you to a build of the master branch, and the `SourceFileFinder` hasn't made it into master yet... but as I said: don't worry, just expect problems like the above.

**Comment by csoltenborn** [comment]
Looks like we are not going to need the `SourceFileFinder` for now (see #65), rendering this issue invalid - closing for now.
