### ISSUE TITLE
Does not work  under VS2015 Update 3

### ISSUE THREAD

**Issue by jagd** [csoltenborn/GoogleTestAdapter#78]
It does not work since update2, neither does the F# one.    Is it possible to fix?
The error message shows:

```
	TestWindowPackage.Initialize failed with exception: 

System.InvalidOperationException: Loading MEF components failed with the following exception: 
An exception was thrown while initializing part "Microsoft.VisualStudio.TestWindow.VsHost.PackageContainer".
Additional diagnostics here: 
MEF Import details for Microsoft.VisualStudio.TestWindow.VsHost.TestWindowPackage

	ContractName	Microsoft.VisualStudio.TestWindow.VsHost.PackageContainer
	RequiredTypeIdentity	Microsoft.VisualStudio.TestWindow.VsHost.PackageContainer
	Satisfied by :
		Microsoft.VisualStudio.TestWindow.VsHost.PackageContainer
 ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.TestWindow.VsHost.PackageContainer".
 ---> System.ArgumentException: The specified argument cannot be empty.
Parameter name: commandContainers
   at Microsoft.VisualStudio.TestWindow.ValidateArg.NotNullOrEmpty[T](IEnumerable`1 arg, String parameterName)
   at Microsoft.VisualStudio.TestWindow.VsHost.PackageContainer..ctor(IServiceProvider serviceProvider, IEnumerable`1 commandContainers)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()
   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.Cast(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastSingleExportToImportType(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToSingleImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportingItem item, Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportDefinition definition, IEnumerable`1 exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.PartManager.TrySetImport(ImportDefinition import, Export[] exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.SatisfyImportsOnce(ComposablePart part)
   at Microsoft.VisualStudio.Composition.NetFxAdapters.CompositionService.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.AttributedModelServices.SatisfyImportsOnce(ICompositionService compositionService, Object attributedPart)
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModelHostExtensions.SatisfyImports[T](T serviceProvider)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()
   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.Cast(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastSingleExportToImportType(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToSingleImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportingItem item, Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportDefinition definition, IEnumerable`1 exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.PartManager.TrySetImport(ImportDefinition import, Export[] exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.SatisfyImportsOnce(ComposablePart part)
   at Microsoft.VisualStudio.Composition.NetFxAdapters.CompositionService.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.AttributedModelServices.SatisfyImportsOnce(ICompositionService compositionService, Object attributedPart)
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModelHostExtensions.SatisfyImports[T](T serviceProvider)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()
   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.Cast(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastSingleExportToImportType(Type type, Export export)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToSingleImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToImportType(Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportingItem item, Export[] exports)
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportDefinition definition, IEnumerable`1 exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.PartManager.TrySetImport(ImportDefinition import, Export[] exports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.SatisfyImportsOnce(ComposablePart part)
   at Microsoft.VisualStudio.Composition.NetFxAdapters.CompositionService.SatisfyImportsOnce(ComposablePart part)
   at System.ComponentModel.Composition.AttributedModelServices.SatisfyImportsOnce(ICompositionService compositionService, Object attributedPart)
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModelHostExtensions.SatisfyImports[T](T serviceProvider)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModelHostExtensions.SatisfyImports[T](T serviceProvider)
   at Microsoft.VisualStudio.TestWindow.VsHost.TestWindowPackage.InitializeContainer()
   at Microsoft.VisualStudio.TestWindow.VsHost.TestWindowPackage.Initialize() 

PackageContainer loaded: False 

Certificates do not match:
	Microsoft.VisualStudio.TestWindow: [Subject]
  CN=Microsoft Corporation, OU=MOPR, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Issuer]
  CN=Microsoft Code Signing PCA, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

```

**Comment by csoltenborn** [comment]
Hm, I have the test adapter running on the latest VS 2015 (Community edition Version 14.0.25431.01 Update 3) without any problems, What precise edition and version of VS are you using?

However, my first guess is that your VS installation is messed up for some reason. Here's what makes me think that way:
* You also have issues with the F# adapter
* Our code is not involved in the above stack trace
* None of our users has reported anything like that so far

I suggest that you try to repair/re-install VS (or try to install our test adapter into a different VS installation) - let us know your results!

**Comment by jagd** [comment]
Hi, thank you for the reply.

- Mein has exactrly the same version  number 14.0.25431.01 under Windows 10.
    -  This error is not only on one PC, I have 3 PCs which has the same windows 10+VS2015. None of them works.
    - However, on another PC with Win7 + VS2015 Update1 works
- The [F# variant of gtest plugin](https://github.com/markusl/GoogleTestRunner) does not work, the reason seems to be related to the missing an old dotNet/F# runtime. I think it may not be directly related to this project. Sorry for the noising.

I'll investigate on more details or maybe fix it later when I have time,

**Comment by csoltenborn** [comment]
One more comment: Have you noticed the ending of your error message? `Certificates do not match:  Microsoft.VisualStudio.TestWindow` might be a hint that for some reason, you have some weird DLLs in your VS installation directory... Not sure about that, though.

**Comment by csoltenborn** [comment]
Have you managed to get our adapter running on all your machines? Can we close this issue?

**Comment by jagd** [comment]
Thank you for asking.

I've tried various approaches, this issue was solved. However the reason was still unknown. If it happens again, I'll investigate the details.

Best regards
